version: "3.9"

services:

  filebeat:
    container_name: filebeat-decoder
    image: docker.elastic.co/beats/filebeat:7.16.3
    user: root
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./elk/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./elk/log-app/authuser:/usr/share/filebeat/logs/authuser
      - ./elk/log-app/course:/usr/share/filebeat/logs/course
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      KIBANA_URL: http://kibana:5601  
    depends_on:
      - elasticsearch
      - kibana

  elasticsearch:
    container_name: elasticsearch-decoder
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml  
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.monitoring.enabled: "true"
    volumes:
      - dados-elasticsearch:/usr/share/elasticsearch/data
      
  kibana:
    container_name: kibana-decoder
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml  
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  postgres-decoder:
    container_name: postgres-decoder
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES="authuser","course","notification","payment"
    ports:
      - "5432:5432"
    networks:
      - backend-decoder
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data-decoder:/var/lib/postgresql/data

  rabbitmq-decoder:
    container_name: rabbitmq-decoder
    image: 'rabbitmq:3-management'
    volumes:
      - dados-rabbitmq:/var/lib/rabbitmq/
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend-decoder
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  eureka-decoder:
    container_name: eureka-decoder
    image: eureka-decoder:latest  
    # build:
    #   context: "./service-registry"
    #   dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend-decoder
    environment:
      eureka.instance.hostname: eureka-decoder
      eureka.client.serviceUrl.defaultZone: http://eureka-decoder:8761/eureka 
      eureka.renewalPercentThreshold: 0.85
      #eureka.instance.preferIpAddress: "true"

  api-gateway-decoder:
    container_name: api-gateway-decoder
    image: juancarllos88/api-gateway:latest  
    ports:
      - "8080:8080"
    networks:
      - backend-decoder
    depends_on:
      - eureka-decoder
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    environment:
      server.port: 8080
      eureka.client.serviceUrl.defaultZone: http://eureka-decoder:8761/eureka
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: authuser-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://host.docker.internal:8087 # ver depois o load balance 
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/ead-authuser/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: course-service
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://host.docker.internal:8082
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/ead-course/**
      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: notification-service
      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://host.docker.internal:8084
      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path=/ead-notification/**

  authuser-decoder:
    container_name: authuser-decoder
    image: juancarllos88/authuser:latest
    ports:
      - "8087:8087"
    networks:
      - backend-decoder
    depends_on:
      - eureka-decoder
      - api-gateway-decoder
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://postgres-decoder:5432/authuser
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
      EUREKA_URL: http://eureka-decoder:8761/eureka
      CLOUDAMQP_URL: amqp://admin:admin@rabbitmq-decoder:5672

  payment-decoder:
    container_name: payment-decoder
    build:
      context: "./payment"
      dockerfile: Dockerfile
    image: juancarllos88/payment:latest
    ports:
      - "8085:8085"
      - "5005:5005"
    networks:
      - backend-decoder
    depends_on:
      - eureka-decoder
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      JDBC_DATABASE_URL: jdbc:postgresql://postgres-decoder:5432/payment
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
      EUREKA_URL: http://ead:ead@eureka-decoder:8761/eureka
      CLOUDAMQP_URL: amqp://admin:admin@rabbitmq-decoder:5672

  # config-server-decoder:
  #   container_name: config-server-decoder
  #   image: juancarllos88/config-server:latest  
  #   ports:
  #     - "8888:8888"
  #   networks:
  #     - backend-decoder
  #   depends_on:
  #     - eureka-decoder
  #   environment:
  #     server.port: 8888
  #     eureka.client.serviceUrl.defaultZone: http://eureka-decoder:8761/eureka

  prometheus-decoder:
    container_name: prometheus-decoder
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - backend-decoder
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana-decoder:
    image: grafana/grafana:latest
    container_name: grafana-decoder
    ports:
      - 3000:3000
    networks:
      - backend-decoder
    depends_on:
      - prometheus-decoder

  zipkin-decoder:
    container_name: zipkin-decoder
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  redis-decoder:
    container_name: redis-decoder
    image: redislabs/redismod
    ports:
      - 6379:6379

  redisinsight-decoder:
    container_name: redisinsight-decoder
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    volumes:
      - redisinsight-data:/db 
    depends_on:
      - redis-decoder

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - backend-decoder
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:6.0.0
    networks:
      - backend-decoder
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:6.0.0
    hostname: control-center
    networks:
      - backend-decoder
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
           


networks:
  backend-decoder:
    driver: bridge 
    #driver: host  #recommended for use only in local development environment.

volumes:
  pg-data-decoder:
  dados-rabbitmq:
  dados-elasticsearch:
  prometheus-data:
  redisinsight-data:

configs:
  elastic_config:
    file: ./elk/elasticsearch/config/elasticsearch.yml
  kibana_config:
    file: ./elk/kibana/config/kibana.yml  
