# filebeat.prospectors:
# - type: log
#   paths:
#     - /var/log/*.log
#   scan_frequency: 1s
#   document_type: json
#   json.message_key: log
#   json.keys_under_root: true
#   json.overwrite_keys: true

# output.logstash:
#   hosts: ["logstash:5044"]

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_URL:elasticsearch:9200}'


# filebeat.inputs:
#   - paths:
#     - '/usr/share/filebeat/*.json'
#     fields_under_root: true
#     fields:
#       tags: ['json']
# output:
#   elasticsearch:
#     hosts: '${ELASTICSEARCH_URL:elasticsearch:9200}'


filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*/*.log
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_keys: true
  json.expand_keys: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_URL:elasticsearch:9200}'
  # username: elastic
  # password: changeme

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#
http.enabled: true
http.host: 0.0.0.0