global:
  scrape_interval: 5s

scrape_configs:
  -   job_name: "api-authuser-job"
      metrics_path: "/ead-authuser/actuator/prometheus"
      static_configs:
        - targets: ["host.docker.internal:8087"]
          labels:
            application: "api-authuser"
  -   job_name: "api-payment-job"
      metrics_path: "/ead-payment/actuator/prometheus"
      static_configs:
        - targets: ["host.docker.internal:8085"]
          labels:
            application: "api-payment"