server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juancarllos88/ead-microservices-config
          default-label: main  
    
ead:
  serviceRegistry:
    username: ead
    password: ead 
    
eureka:
  client:
    service-url:
      default-zone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
