server:
  port: 8087
  servlet:
   context-path: '/ead-authuser/'
  
spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: ead-authuser
    password: ead-authuser
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        
logging:
  level:
    br.com.ead: TRACE
    #root: DEBUG
    #DETALHES DE REQUEST WEB
    org.springframework.web: DEBUG
    org.hibernate: INFO
    
api:
  url:
    course: 'http://ead-course-service/ead-course'    
    
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8087/eureka'
  instance:
    hostname: localhost                 