server:
  port: 8085
  servlet:
    context-path: '/ead-payment/'

spring:
  application:
    name: ead-payment-service

  datasource:
    url:  jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqp://admin:admin@localhost:5672

ead:
  auth:
    jwtSecret: ead-projeto-decoder
  serviceRegistry:
    username: ${EUREKA_USERNAME:ead}
    password: ${EUREKA_PASSWORD:ead}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,metrics,prometheus,refresh"
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    refresh:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka}
  instance:
    hostname: ${APP_DOMAIN_NAME:localhost}