server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
  
spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqp://admin:admin@localhost:5672
      
          
ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEvent: ead.userevent
      notificationCommand: ead.notificationcommand
    queue:
      userEvent:
        course: ead.userevent.ms.course
    routingKey:
      notificationCommand: ms.subscription.notification              
          
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8087/eureka'
  instance:
    hostname: localhost      